spring.application.name=TwinScheduler

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=root
spring.datasource.password=qczY7zngfMzxdr4wgPSRnVG69yp8RsAT9MN5ZdAZ9TfU
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20


# Scheduling Configuration (milliseconds)
scheduler.healthcheck.fixedRate=60000
scheduler.autoscale.fixedRate=60000
scheduler.autoscale.minInstances=2
scheduler.autoscale.imageName=Twin-Instance-RnD


# Endpoint Configuration
endpoints.lambda.healthcheck=https://hd2y7yqc43.execute-api.us-east-1.amazonaws.com/default/HealthCheck
endpoints.lambda.healthcheck.retries=5
endpoints.lambda.healthcheck.delay=120000
endpoints.autoscale=https://hd2y7yqc43.execute-api.us-east-1.amazonaws.com/default/AutoScaler

#Extractor configs
extractor.application.port=8080

#twin.application.name=java.exe
# Thread Pool Configuration
threadpool.size=10