spring.application.name=TwinScheduler

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Scheduling Configuration (milliseconds)
scheduler.healthcheck.fixedRate=60000
scheduler.autoscale.fixedRate=60000
scheduler.autoscale.minInstances=2
scheduler.autoscale.imageName=twin-autoscaler-image


# Endpoint Configuration
endpoints.lambda.healthcheck=https://1i4vzoi726.execute-api.us-east-1.amazonaws.com/default/twinHealthCheck
endpoints.autoscale=https://1i4vzoi726.execute-api.us-east-1.amazonaws.com/twinAutoscalerStage/TwinAutoScaler

#Extractor configs
extractor.application.port=8080

twin.application.name=java.exe
# Thread Pool Configuration
threadpool.size=10
