spring.application.name=TwinScheduler

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.maximum-pool-size=20


# Scheduling Configuration (milliseconds)
scheduler.healthcheck.fixedRate=60000
scheduler.autoscale.fixedRate=60000
scheduler.autoscale.minInstances=2
scheduler.autostart.minShutdownInstances=0
scheduler.autoscale.imageName=Twin-Instance-RnD-v3.1

# Endpoint Configuration
endpoints.lambda.healthcheck=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/HealthCheck
endpoints.lambda.healthcheck.retries=10
endpoints.lambda.healthcheck.delay=30000
endpoints.autoscale=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/AutoScaler
endpoints.autostart=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/AutoRestart
endpoints.autostop=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/AutoStop
endpoints.statecheck=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/StateChecker
endpoints.autoterminate=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/AutoTerminater
endpoints.shutdownpooladder=https://mq3ivdouyj.execute-api.us-east-2.amazonaws.com/default/ShutdownPoolAdder

#Extractor configs
extractor.application.port=8080

#Extractor configs
extractor.application.port=8080

#twin.application.name=java.exe
# Thread Pool Configuration
threadpool.size=10